hassio-addons/addon-phpmyadmin

- phpmyadmin/Dockerfile
Adds the php7-curl package.
Should fix #4
> ✨ Add php7-curl

- phpmyadmin/rootfs/etc/phpmyadmin/config.inc.php
This disables the option to check for newer versions by default.
Users won't have any use for this anyway.
NA
> :fire: Disable version check

- phpmyadmin/Dockerfile
Add php7-iconv to fix issue with Monitor page
Fixes #13
> 🔨 Add php7-iconv

- LICENSE.md
- README.md
- phpmyadmin/.README.j2
- phpmyadmin/DOCS.md
> Happy New Year

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades the add-on base image to 9.1.0
> Upgrade add-on base image to 9.1.0

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrade add-on base image to 9.1.1
> Upgrade add-on base image to 9.1.1

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
> Upgrade add-on base image to 9.1.2

- phpmyadmin/Dockerfile
> :arrow_up: Upgrades php7 to 7.4.15-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v9.1.7
> ⬆️ Upgrades add-on base image to v9.1.7

- phpmyadmin/Dockerfile
https://www.phpmyadmin.net/news/2021/2/24/phpmyadmin-510-released/
> ⬆️ Upgrades phpMyAdmin to 5.1.0

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v9.2.0
> Upgrades add-on base image to v9.2.0

- phpmyadmin/translations/en.yaml
Add add-on translation support
> Add add-on translation support

- phpmyadmin/Dockerfile
Upgrades mariadb-client to 10.5.9-r0
> ⬆️ Upgrades mariadb-client to 10.5.9-r0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php7 to 7.4.19-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v9.2.1
> ⬆️  Upgrades add-on base image to v9.2.1

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v9.2.2
> ⬆️ Upgrades add-on base image to v9.2.2

- phpmyadmin/Dockerfile
Upgrades phpMyAdmin to 5.1.1
https://www.phpmyadmin.net/news/2021/6/4/phpmyadmin-511-released/
> ⬆️ Upgrades phpMyAdmin to 5.1.1

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v10.0.0
> ⬆️ Upgrades add-on base image to v10.0.0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php7 to 7.4.21-r0

- phpmyadmin/Dockerfile
Upgrades mariadb-client to 10.5.12-r0
> ⬆️ Upgrades mariadb-client to 10.5.12-r0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php7 to 7.4.22-r0

- phpmyadmin/rootfs/etc/nginx/nginx.conf
Less chatter in the logs by disabling access log output
> 🔥 Less logging by removing access log from log ouput

- phpmyadmin/config.json
> 🏎 Enable streaming mode for Ingress

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to v10.0.1
> ⬆️ Upgrades add-on base image to v10.0.1

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.11-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.json
Upgrades add-on base image to 10.1.0
> ⬆️ Upgrades add-on base image to 10.1.0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.12-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 10.2.1
> ⬆️ Upgrades add-on base image to 10.2.1

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 10.2.2
> ⬆️ Upgrades add-on base image to 10.2.2

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 11.0.0
> ⬆️ Upgrades add-on base image to 11.0.0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.14-r0

- LICENSE.md
- README.md
- phpmyadmin/.README.j2
- phpmyadmin/DOCS.md
> :fireworks: Updates maintenance/license year to 2022

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 11.0.1
> ⬆️ Upgrades add-on base image to 11.0.1

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.16-r0

- phpmyadmin/Dockerfile
Upgrades add-on base image to 11.1.0
> ⬆️ Upgrades add-on base image to 11.1.0

- .github/workflows/deploy.yaml
- phpmyadmin/build.yaml
- phpmyadmin/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- phpmyadmin/Dockerfile
https://www.phpmyadmin.net/news/2022/2/11/phpmyadmin-4910-and-513-are-released/
> ⬆️ Upgrades phpMyAdmin to 5.1.3

- phpmyadmin/DOCS.md
To make it easier to find the add-on
> :books: Add My buttons to documentation

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
- phpmyadmin/rootfs/etc/cont-init.d/nginx.sh
- phpmyadmin/rootfs/etc/cont-init.d/phpmyadmin.sh
- phpmyadmin/rootfs/etc/services.d/nginx/finish
- phpmyadmin/rootfs/etc/services.d/nginx/run
- phpmyadmin/rootfs/etc/services.d/php-fpm/finish
- phpmyadmin/rootfs/etc/services.d/php-fpm/run
Upgrades add-on base image to 12.0.0
> ⬆️ Upgrades add-on base image to 12.0.0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.20-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 12.2.1
> ⬆️ Upgrades add-on base image to 12.2.1

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
Upgrades add-on base image to 12.2.3
> ⬆️ Upgrades add-on base image to 12.2.3

- phpmyadmin/Dockerfile
> ⬆️ Upgrades mariadb-client to 10.6.10-r0

- phpmyadmin/Dockerfile
> ⬆️ Upgrades php8 to 8.0.25-r0

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.6

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
> ⬆️ Upgrades add-on base image to 13.0.0

- phpmyadmin/Dockerfile
- phpmyadmin/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.3

- phpmyadmin/Dockerfile
https://www.phpmyadmin.net/news/2023/2/8/phpmyadmin-4911-and-521-are-released/
> ⬆️ Upgrades phpMyAdmin to 5.2.1

- phpmyadmin/DOCS.md
> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> Fix broken URL

- README.md
- phpmyadmin/build.yaml
- phpmyadmin/config.yaml
> Drop support for armhf & i386

- LICENSE.md
- README.md
- phpmyadmin/.README.j2
- phpmyadmin/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- LICENSE.md
- README.md
- phpmyadmin/.README.j2
- phpmyadmin/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
